=== LuminexLCE/lamplibrary/device_description.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsld="../ns_description" xmlns:decl="../ns_declarations" targetNamespace="../ns_description" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="../ns_declarations" schemaLocation="../lamplibrary_xml/declarations.xsd"/>
	<xs:element name="DeviceDescription" type="xsld:DeviceDescrType">
		<xs:annotation>
			<xs:documentation>Root element: Device description</xs:documentation>
		</xs:annotation>
		<xs:unique name="UniqueChannelNo">
			<xs:selector xpath="./xsld:ChannelDefinition/xsld:Channel"/>
			<xs:field xpath="@ChannelNo"/>
		</xs:unique>
		<xs:unique name="UniqueChannelName">
			<xs:selector xpath="./xsld:ChannelDefinition/xsld:Channel"/>
			<xs:field xpath="@Name"/>
		</xs:unique>
		<xs:keyref name="MasterChannelNoRef" refer="xsld:UniqueChannelNo">
			<xs:selector xpath="./xsld:ChannelDefinition/xsld:Channel"/>
			<xs:field xpath="@MasterChannelNo"/>
		</xs:keyref>
		<xs:unique name="UniqueDepName">
			<xs:selector xpath="./xsld:DependencyDeclaration/xsld:Dependency"/>
			<xs:field xpath="@Name"/>
		</xs:unique>
		<xs:keyref name="DepChannelNameRef" refer="xsld:UniqueChannelName">
			<xs:selector xpath="./xsld:DependencyDeclaration/xsld:Dependency"/>
			<xs:field xpath="@ChannelName"/>
		</xs:keyref>
		<xs:keyref name="FuncDescrChannelNameRef" refer="xsld:UniqueChannelName">
			<xs:selector xpath="./xsld:ParameterDefinition/xsld:FuncDiscr"/>
			<xs:field xpath="@ChannelName"/>
		</xs:keyref>
		<xs:keyref name="DependencyNameRef" refer="xsld:UniqueDepName">
			<xs:selector xpath="ParameterDefinition/xsld:FuncDiscr/xsld:Range/xsld:Dependency"/>
			<xs:field xpath="@Name"/>
		</xs:keyref>
	</xs:element>
	<xs:attributeGroup name="ManInfoGroup">
		<xs:attribute name="Manufacturer" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Manufacturer name</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Model" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Manufacturers model name</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Firmware" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Device Firmware version</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Mode" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Mode, e.g. 16bit, 8bit, extended,...</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>
	<xs:attributeGroup name="RangeGroup">
		<xs:annotation>
			<xs:documentation>Group of attributes used in a DMX range explanation</xs:documentation>
		</xs:annotation>
		<xs:attribute name="SubName" type="decl:SubNameType" use="optional">
			<xs:annotation>
				<xs:documentation>Name describing the range. E.g. Slot1, Slot2, Reset, LampOn, ... -> To map with different device types</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Semantic" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Semantic description. E.g. Open/White, Breaks, Green, Leaves, ...</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Unit" type="decl:UnitType" use="optional">
			<xs:annotation>
				<xs:documentation>Units of the physical values. E.g degree, RPM, BPM, cm,...</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="DmxBottom" type="xs:unsignedByte" use="required">
			<xs:annotation>
				<xs:documentation>Bottom value of the DMX range</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="PhysBottom" type="xs:decimal" use="optional">
			<xs:annotation>
				<xs:documentation>Value of the Physical representation of the Dmx bottom value, in Unit</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="DmxTop" type="xs:unsignedByte" use="required">
			<xs:annotation>
				<xs:documentation>Top value of the DMX range</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="PhysTop" type="xs:decimal" use="optional">
			<xs:annotation>
				<xs:documentation>Value of the Physical representation of the Dmx top value, in Unit</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="DmxToPhys" type="decl:TransferType" use="required">
			<xs:annotation>
				<xs:documentation>Transfert function between DMX value and Physical value.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Time" type="xs:long" use="optional">
			<xs:annotation>
				<xs:documentation>Time to stay in this range to validate the setting, in mili seconds (ms). 0 or not filled in if not applicable</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>
	<xs:complexType name="DeviceDescrType">
		<xs:annotation>
			<xs:documentation>Type description for root element</xs:documentation>
		</xs:annotation>
		<xs:all>
			<xs:element name="ManufacturerInfo">
				<xs:complexType>
					<xs:attributeGroup ref="xsld:ManInfoGroup"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="PhysicalProperties" type="xsld:PhysPropType"/>
			<xs:element name="ChannelDefinition">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="xsld:ChanDefType">
							<xs:attribute name="Align" type="xs:nonNegativeInteger" use="required"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="DependencyDeclaration" minOccurs="0">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="Dependency">
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="xsld:DependencyType"/>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ParameterDefinition" type="xsld:ParamType" minOccurs="0"/>
			<xs:element name="MacroDefinition" minOccurs="0" type="xsld:MacroDefType">
			</xs:element>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="ManInfoType">
		<xs:annotation>
			<xs:documentation>info about manufacturer, lamp code, physical properties</xs:documentation>
		</xs:annotation>
	</xs:complexType>
	<xs:complexType name="ChanDefType">
		<xs:annotation>
			<xs:documentation>enumeration of all the channels</xs:documentation>
		</xs:annotation>
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="Channel" type="xsld:ChanType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PhysValType">
		<xs:sequence>
			<xs:element name="Unit" type="decl:UnitType">
				<xs:annotation>
					<xs:documentation>Unit, e.g mm, cm, degree,...</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Value" type="xs:decimal">
				<xs:annotation>
					<xs:documentation>decimal value</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PhysPropType">
		<xs:sequence>
			<xs:element name="Weight" type="xsld:PhysValType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Total weight of device</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Geometry" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Exterior dimensions</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Width" type="xsld:PhysValType" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Total Width</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="Depth" type="xsld:PhysValType" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Total Depth</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="Height" type="xsld:PhysValType" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Total Hight</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Lens" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Lens and beam definition</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence minOccurs="0">
						<xs:element name="LensType" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Lens type, e.g. Standard, wide, narrow</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="Diameter" type="xsld:PhysValType" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Lens diameter</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="BeamPos" type="xsld:RefBeamType" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Lens positioning relative to zero reference according to lens position convention document.</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="LensName" type="xs:string" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Lens Name as defined by manufacturer</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="IntensityCurve" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Intensity curve to provide different luminous intensity with different angles</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="Angle" type="xs:decimal">
										<xs:annotation>
											<xs:documentation>Lens or zoom angle in degree. 0 = narrow</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="Intensity" type="xs:decimal">
										<xs:annotation>
											<xs:documentation>Light emission intensity in Lumen</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Lamp" type="xsld:LampType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Lamp definition</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute type="decl:KindOfDeviceType" name="Type" use="required">
			<xs:annotation>
				<xs:documentation>Set the type of device: Yoke, Mirro, Scroller, Dimmer,...	</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="RangeType">
		<xs:attributeGroup ref="xsld:RangeGroup"/>
	</xs:complexType>
	<xs:complexType name="RefBeamType">
		<xs:sequence minOccurs="0">
			<xs:element name="XOffset" type="xsld:PhysValType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>X offset from zero reference</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="YOffset" type="xsld:PhysValType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Y offset from zero reference</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ZOffset" type="xsld:PhysValType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Z offset from zero reference</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="AlfaOffset" type="xsld:PhysValType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Rotation around X axis</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="BetaOffset" type="xsld:PhysValType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Rotation around Y axis</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="GammaOffset" type="xsld:PhysValType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ParamType">
		<xs:annotation>
			<xs:documentation>lamp parameters: position, intensity, colour, beam, control</xs:documentation>
		</xs:annotation>
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="FuncDiscr">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="xsld:FuncDiscrType"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ChanType">
		<xs:attribute name="ChannelNo" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:positiveInteger"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Name" type="decl:ChanNameType" use="required"/>
		<xs:attribute name="Semantic" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Category" type="decl:Category" use="required"/>
		<xs:attribute name="HighlightValue" type="xs:unsignedByte" default="0"/>
		<xs:attribute name="BitRes" type="decl:BitRes" default="8"/>
		<xs:attribute name="ByteNo" type="decl:ByteNo" default="0"/>
		<xs:attribute name="DefaultValue" type="xs:unsignedByte" default="0"/>
		<xs:attribute name="MasterChannelNo" type="xs:positiveInteger" use="optional"/>
	</xs:complexType>
	<xs:complexType name="FuncDiscrType">
		<xs:sequence>
			<xs:element name="Range" type="xsld:RangeLevel2Type" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="ChannelName" type="decl:ChanNameType" use="required"/>
	</xs:complexType>
	<xs:complexType name="DependencyType">
		<xs:annotation>
			<xs:documentation>Dependency type description</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Range" type="xsld:RangeLevel1Type" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="Name" type="xs:string" use="required"/>
		<xs:attribute name="ChannelName" type="decl:ChanNameType" use="required"/>
	</xs:complexType>
	<xs:complexType name="RangeLevel2Type">
		<xs:annotation>
			<xs:documentation>DMX Range attributes with dependency</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="xsld:RangeLevel1Type">
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element name="Dependency">
						<xs:complexType>
							<xs:attribute name="Name" type="xs:string" use="required"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="RangeLevel1Type">
		<xs:annotation>
			<xs:documentation>DMX Range attributes without dependency</xs:documentation>
		</xs:annotation>
		<xs:attributeGroup ref="xsld:RangeGroup"/>
	</xs:complexType>
	<xs:complexType name="LampType">
		<xs:annotation>
			<xs:documentation>Lamp type description, model, power, temp</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Type" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Type, e.g. HMI, MSD,...</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Model" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Complete name and model, e.g. Osram HMI 1200 W/S</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Power" type="xs:decimal" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Power consumption in Watts</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ColorTemp" type="xs:decimal" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Colour temperature in Kelvin (K)</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MacroDefType">
		<xs:sequence>
			<xs:element name="Macro" maxOccurs="unbounded" type="xsld:MacroType">
				
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MacroType">
		<xs:sequence>
			<xs:element name="MacroStep" maxOccurs="unbounded">
				
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Name" use="required" type="xs:string">
			
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== LuminexLCE/lamplibrary/device_library/movitec/sl250/sl250.xml
<?xml version="1.0" encoding="UTF-8"?>
<DeviceDescription xmlns="../ns_description" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="../ns_description
	../../../device_description.xsd">
	<ManufacturerInfo Manufacturer="Movitec" Model="SL 250" Firmware=""/>
	<PhysicalProperties Type="YokeSpot">
		<Weight>
			<Unit>kg</Unit>
			<Value>16</Value>
		</Weight>
		<Geometry>
			<Width>
				<Unit>mm</Unit>
				<Value>428</Value>
			</Width>
			<Depth>
				<Unit>mm</Unit>
				<Value>379</Value>
			</Depth>
			<Height>
				<Unit>mm</Unit>
				<Value>476</Value>
			</Height>
		</Geometry>
		<Lamp>
			<Type>MSD</Type>
			<Model>MSD/HSD 230V/250W GY-9.5</Model>
			<Power>250</Power>
		</Lamp>
	</PhysicalProperties>
	<ChannelDefinition Align="16">
		<Channel ChannelNo="1" Name="Pan" Semantic="Pan" Category="Position" BitRes="16" DefaultValue="128" ByteNo="1"/>
		<Channel ChannelNo="2" Name="PanFine" Semantic="Pan Fine" Category="Position" BitRes="16" ByteNo="0" MasterChannelNo="1"/>
		<Channel ChannelNo="3" Name="Tilt" Semantic="Tilt" Category="Position" BitRes="16" DefaultValue="128" ByteNo="1"/>
		<Channel ChannelNo="4" Name="TiltFine" Semantic="Tilt Fine" Category="Position" BitRes="16" ByteNo="0" MasterChannelNo="3"/>
		<Channel ChannelNo="5" Name="MSpeed" Semantic="MSpeed" Category="Control" DefaultValue="0"/>
		<Channel ChannelNo="6" Name="LampCTRL" Semantic="Lamp Function" Category="Control" DefaultValue="255"/>
		<Channel ChannelNo="7" Name="Colour1" Semantic="Colour Wheel" Category="Colour" DefaultValue="0"/>
		<Channel ChannelNo="9" Name="Prism1" Semantic="Prism" Category="Beam" DefaultValue="0"/>
		<Channel ChannelNo="10" Name="Prism1Rot" Semantic="Prism Rotation" Category="Beam" DefaultValue="0"/>
		<Channel ChannelNo="11" Name="Gobo1" Semantic="Gobo" Category="Beam" DefaultValue="0"/>
		<Channel ChannelNo="12" Name="Gobo1Rot" Semantic="Gobo Rotation" Category="Beam" DefaultValue="0"/>
		<Channel ChannelNo="14" Name="Focus" Semantic="Focus" Category="Beam" DefaultValue="0"/>
		<Channel ChannelNo="15" Name="Shutter" Semantic="Shutter" Category="Beam" DefaultValue="255"/>
		<Channel ChannelNo="16" Name="Intensity1" Semantic="Dimmer" Category="Intensity" DefaultValue="255"/>
	</ChannelDefinition>
	<DependencyDeclaration/>
	<ParameterDefinition>
		<FuncDiscr ChannelName="Pan">
			<Range Unit="degrees" Semantic="Pan" DmxToPhys="proportionalUp" DmxBottom="0" DmxTop="255" PhysBottom="-265" PhysTop="265"/>
		</FuncDiscr>
		<FuncDiscr ChannelName="Tilt">
			<Range Unit="degrees" Semantic="Tilt" DmxToPhys="proportionalUp" DmxBottom="0" DmxTop="255" PhysBottom="-140" PhysTop="140"/>
		</FuncDiscr>
		<FuncDiscr ChannelName="MSpeed">
			<Range SubName="MoveSpeedTrackMax" Semantic="Max speed (tracking)" DmxBottom="0" DmxTop="0" DmxToPhys="fix"/>
			<Range SubName="MoveSpeedVector" Semantic="Speed (vector)" DmxBottom="1" DmxTop="249" DmxToPhys="proportionalDown"/>
			<Range SubName="MoveBlackout" Semantic="Move speed blackout" DmxBottom="250" DmxTop="255" DmxToPhys="fix"/>
		</FuncDiscr>
		<FuncDiscr ChannelName="LampCTRL">
			<Range SubName="FanSpeed" Semantic="Fan Speed" DmxBottom="0" DmxTop="127" DmxToPhys="proportionalDown"/>
			<Range SubName="LampOnReset" Semantic="LampOn/ reset" DmxBottom="128" DmxTop="139" DmxToPhys="fix"/>
			<Range SubName="NoFunction" Semantic="No Function" DmxBottom="140" DmxTop="229" DmxToPhys="fix"/>
			<Range SubName="LampOff" Semantic="LampOff" DmxBottom="230" DmxTop="239" DmxToPhys="fix" Time="3000"/>
			<Range SubName="NoFunction" Semantic="No Function" DmxBottom="240" DmxTop="255" DmxToPhys="fix"/>
		</FuncDiscr>
		<FuncDiscr ChannelName="Colour1">
			<Range SubName="Slot_01" Semantic="Open/white" DmxBottom="0" DmxTop="9" DmxToPhys="fix"/>
			<Range SubName="Slot_02" Semantic="UV filter" DmxBottom="10" DmxTop="20" DmxToPhys="fix"/>
			<Range SubName="Slot_03" Semantic="Red" DmxBottom="21" DmxTop="31" DmxToPhys="fix"/>
			<Range SubName="Slot_04" Semantic="Cyan" DmxBottom="32" DmxTop="41" DmxToPhys="fix"/>
			<Range SubName="Slot_05" Semantic="Green" DmxBottom="42" DmxTop="52" DmxToPhys="fix"/>
			<Range SubName="Slot_06" Semantic="Magenta" DmxBottom="53" DmxTop="63" DmxToPhys="fix"/>
			<Range SubName="Slot_07" Semantic="Light Blue" DmxBottom="64" DmxTop="73" DmxToPhys="fix"/>
			<Range SubName="Slot_08" Semantic="Yellow" DmxBottom="74" DmxTop="84" DmxToPhys="fix"/>
			<Range SubName="Slot_09" Semantic="Green" DmxBottom="85" DmxTop="95" DmxToPhys="fix"/>
			<Range SubName="Slot_10" Semantic="Pink" DmxBottom="96" DmxTop="105" DmxToPhys="fix"/>
			<Range SubName="Slot_11" Semantic="Blue" DmxBottom="106" DmxTop="116" DmxToPhys="fix"/>
			<Range SubName="Slot_12" Semantic="Orange" DmxBottom="117" DmxTop="127" DmxToPhys="fix"/>
			<Range SubName="SpinForward" Semantic="SpinForward" DmxBottom="128" DmxTop="190" DmxToPhys="proportionalDown"/>
			<Range SubName="SpinStop" Semantic="SpinStop" DmxBottom="191" DmxTop="192" DmxToPhys="fix"/>
			<Range SubName="SpinBackward" Semantic="SpinBackward" DmxBottom="193" DmxTop="255" DmxToPhys="proportionalUp"/>
		</FuncDiscr>
		<FuncDiscr ChannelName="Prism1">
			<Range SubName="Open" Semantic="Open (hole)" DmxBottom="0" DmxTop="95" DmxToPhys="fix"/>
			<Range SubName="PrismIn3" Semantic="3-facet rot prism" DmxBottom="96" DmxTop="159" DmxToPhys="fix"/>
			<Range SubName="Macro_01" Semantic="Macro 1" DmxBottom="160" DmxTop="167" DmxToPhys="fix"/>
			<Range SubName="Macro_02" Semantic="Macro 2" DmxBottom="168" DmxTop="175" DmxToPhys="fix"/>
			<Range SubName="Macro_03" Semantic="Macro 3" DmxBottom="176" DmxTop="183" DmxToPhys="fix"/>
			<Range SubName="Macro_04" Semantic="Macro 4" DmxBottom="184" DmxTop="191" DmxToPhys="fix"/>
			<Range SubName="Macro_05" Semantic="Macro 5" DmxBottom="192" DmxTop="199" DmxToPhys="fix"/>
			<Range SubName="Macro_06" Semantic="Macro 6" DmxBottom="200" DmxTop="207" DmxToPhys="fix"/>
			<Range SubName="Macro_07" Semantic="Macro 7" DmxBottom="208" DmxTop="215" DmxToPhys="fix"/>
			<Range SubName="Macro_08" Semantic="Macro 8" DmxBottom="216" DmxTop="223" DmxToPhys="fix"/>
			<Range SubName="Macro_09" Semantic="Macro 9" DmxBottom="224" DmxTop="231" DmxToPhys="fix"/>
			<Range SubName="Macro_10" Semantic="Macro 10" DmxBottom="232" DmxTop="239" DmxToPhys="fix"/>
			<Range SubName="Macro_11" Semantic="Macro 11" DmxBottom="240" DmxTop="247" DmxToPhys="fix"/>
			<Range SubName="Macro_12" Semantic="Macro 12" DmxBottom="248" DmxTop="255" DmxToPhys="fix"/>
		</FuncDiscr>
		<FuncDiscr ChannelName="Prism1Rot">
			<Range SubName="RotStop" Semantic="No rotation" DmxBottom="0" DmxTop="0" DmxToPhys="fix"/>
			<Range SubName="RotForward" Semantic="RotForward" DmxBottom="1" DmxTop="126" DmxToPhys="proportionalDown"/>
			<Range SubName="RotStop" Semantic="No rotation" DmxBottom="127" DmxTop="128" DmxToPhys="fix"/>
			<Range SubName="RotBackward" Semantic="RotBackward" DmxBottom="129" DmxTop="255" DmxToPhys="proportionalUp"/>
		</FuncDiscr>
		<FuncDiscr ChannelName="Gobo1">
			<Range SubName="Slot_01" Semantic="Open" DmxBottom="0" DmxTop="31" DmxToPhys="fix"/>
			<Range SubName="Slot_02" Semantic="Gobo 1" DmxBottom="32" DmxTop="63" DmxToPhys="fix"/>
			<Range SubName="Slot_03" Semantic="Gobo 2" DmxBottom="64" DmxTop="95" DmxToPhys="fix"/>
			<Range SubName="Slot_04" Semantic="Gobo 3" DmxBottom="96" DmxTop="127" DmxToPhys="fix"/>
			<Range SubName="Slot_05" Semantic="Gobo 4" DmxBottom="128" DmxTop="159" DmxToPhys="fix"/>
			<Range SubName="Slot_06" Semantic="Gobo 5" DmxBottom="160" DmxTop="191" DmxToPhys="fix"/>
			<Range SubName="Slot_07" Semantic="Gobo 6" DmxBottom="192" DmxTop="223" DmxToPhys="fix"/>
			<Range SubName="SpinForward" Semantic="SpinForward" DmxBottom="224" DmxTop="255" DmxToPhys="proportionalUp"/>
		</FuncDiscr>
		<FuncDiscr ChannelName="Gobo1Rot">
			<Range SubName="Index" Semantic="Gobo indexing" DmxBottom="0" DmxTop="127" DmxToPhys="proportionalUp"/>
			<Range SubName="RotForward" Semantic="RotForward" DmxBottom="128" DmxTop="190" DmxToPhys="proportionalDown"/>
			<Range SubName="RotStop" Semantic="No rotation" DmxBottom="191" DmxTop="192" DmxToPhys="fix"/>
			<Range SubName="RotBackward" Semantic="RotBackward" DmxBottom="193" DmxTop="255" DmxToPhys="proportionalUp"/>
		</FuncDiscr>
		<FuncDiscr ChannelName="Focus">
			<Range Semantic="Focus" DmxBottom="0" DmxTop="255" DmxToPhys="proportionalDown"/>
		</FuncDiscr>
		<FuncDiscr ChannelName="Shutter">
			<Range SubName="Closed" Semantic="Shutter closed" DmxBottom="0" DmxTop="31" DmxToPhys="fix"/>
			<Range SubName="Open" Semantic="Shutter open" DmxBottom="32" DmxTop="63" DmxToPhys="fix"/>
			<Range SubName="Strobe" Semantic="Periodic strobe" DmxBottom="64" DmxTop="95" DmxToPhys="proportionalUp"/>
			<Range SubName="Open" Semantic="Shutter open" DmxBottom="96" DmxTop="127" DmxToPhys="fix"/>
			<Range SubName="StrobePulse" Semantic="Pulse effect" DmxBottom="128" DmxTop="159" DmxToPhys="fix"/>
			<Range SubName="Open" Semantic="Shutter open" DmxBottom="160" DmxTop="191" DmxToPhys="fix"/>
			<Range SubName="StrobeRandom" Semantic="Random strobe" DmxBottom="192" DmxTop="223" DmxToPhys="proportionalUp"/>
			<Range SubName="Open" Semantic="Shutter open" DmxBottom="224" DmxTop="255" DmxToPhys="fix"/>
		</FuncDiscr>
		<FuncDiscr ChannelName="Intensity1">
			<Range Semantic="Intensity" DmxBottom="0" DmxTop="255" DmxToPhys="proportionalUp"/>
		</FuncDiscr>
	</ParameterDefinition>
</DeviceDescription>

=== LuminexLCE/lamplibrary/device_library/claypaky/alpha_profile_1200_stnd/alpha_profile_1200_stnd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by test (test) -->
<DeviceDescription xmlns="../ns_description" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="../ns_description
	../../../device_description.xsd">
	<ManufacturerInfo Manufacturer="Clay Paky" Model="AlphaProfile 1200 Stnd" Mode="Standard"/>
	<PhysicalProperties Type="YokeSpot"/>
	<ChannelDefinition Align="32">
		<Channel ChannelNo="1" Name="Cyan" Semantic="Cyan" Category="Colour" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="2" Name="Magenta" Semantic="Magenta" Category="Colour" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="3" Name="Yellow" Semantic="Yellow" Category="Colour" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="4" Name="CTO" Semantic="CTO" Category="Colour" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="5" Name="Colour1" Semantic="Colour Wheel" Category="Colour" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="6" Name="Shutter" Semantic="Stop / Strobe" Category="Control" DefaultValue="255" HighlightValue="255"/>
		<Channel ChannelNo="7" Name="Intensity1" Semantic="Dimmer" Category="Intensity" DefaultValue="0" HighlightValue="255"/>
		<Channel ChannelNo="8" Name="Iris" Semantic="Iris" Category="Beam" DefaultValue="255" HighlightValue="255"/>
		<Channel ChannelNo="9" Name="Gobo1" Semantic="Static Gobo Wheel" Category="Beam" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="10" Name="Gobo2" Semantic="Rotating Gobo Wheel" Category="Beam" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="11" Name="Gobo2Rot" Semantic="Gobo Rotation" Category="Beam" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="12" Name="Framing1a" Semantic="Blade Up 1" Category="Beam" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="13" Name="Framing1b" Semantic="Blade Up 2" Category="Beam" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="14" Name="Framing2a" Semantic="Blade Down 1" Category="Beam" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="15" Name="Framing2b" Semantic="Blade Down 2" Category="Beam" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="16" Name="Framing3a" Semantic="Blade Right 1" Category="Beam" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="17" Name="Framing3b" Semantic="Blade Right 2" Category="Beam" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="18" Name="Framing4a" Semantic="Blade Left 1" Category="Beam" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="19" Name="Framing4b" Semantic="Blade Left 2" Category="Beam" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="20" Name="FramingRot" Semantic="Framing Rotation" Category="Beam" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="21" Name="Effect1" Semantic="Frost/Prism/Animation" Category="Beam" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="22" Name="Effect1Rot" Semantic="Prism/Anim Rotation" Category="Beam" DefaultValue="0" HighlightValue="0"/>
		<Channel ChannelNo="23" Name="Focus" Semantic="Focus" Category="Beam" HighlightValue="0"/>
		<Channel ChannelNo="24" Name="Zoom" Semantic="Zoom" Category="Beam"/>
		<Channel ChannelNo="25" Name="Pan" Semantic="Pan" Category="Position" DefaultValue="128"/>
		<Channel ChannelNo="26" Name="Tilt" Semantic="Tilt" Category="Position" DefaultValue="128"/>
		<Channel ChannelNo="27" Name="Control" Semantic="Reset" Category="Control"/>
		<Channel ChannelNo="28" Name="LampCTRL" Semantic="Lamp Control" Category="Control"/>
		<Channel ChannelNo="29" Name="PanTiltSpeed" Semantic="Pan/Tilt Time" Category="Control"/>
		<Channel ChannelNo="30" Name="ColourTime" Semantic="Colour Time" Category="Control"/>
		<Channel ChannelNo="31" Name="BeamTime" Semantic="Beam Time" Category="Control"/>
		<Channel ChannelNo="32" Name="GoboTime" Semantic="Gobo Time" Category="Control"/>
	</ChannelDefinition>
	<DependencyDeclaration> </DependencyDeclaration>
	<ParameterDefinition/>
</DeviceDescription>
